//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "ERROR"
 */
public class ErrorStmt implements Node {
   public NodeToken f0;

   public ErrorStmt(NodeToken n0) {
      f0 = n0;
   }

   public ErrorStmt() {
      f0 = new NodeToken("ERROR");
   }

   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
}

