//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "LE"
 *       | "NE"
 *       | "PLUS"
 *       | "MINUS"
 *       | "TIMES"
 *       | "DIV"
 */
public class Operator implements Node {
   public NodeChoice f0;

   public Operator(NodeChoice n0) {
      f0 = n0;
   }

   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
}

