//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "NOOP"
 */
public class NoOpStmt implements Node {
   public NodeToken f0;

   public NoOpStmt(NodeToken n0) {
      f0 = n0;
   }

   public NoOpStmt() {
      f0 = new NodeToken("NOOP");
   }

   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
}

