//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ( ( Label() )? Stmt() )*
 */
public class StmtList implements Node {
   public NodeListOptional f0;

   public StmtList(NodeListOptional n0) {
      f0 = n0;
   }

   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
}

