//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "TEMP"
 * f1 -> IntegerLiteral()
 */
public class Temp implements Node {
   public NodeToken f0;
   public IntegerLiteral f1;

   public Temp(NodeToken n0, IntegerLiteral n1) {
      f0 = n0;
      f1 = n1;
   }

   public Temp(IntegerLiteral n0) {
      f0 = new NodeToken("TEMP");
      f1 = n0;
   }

   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
}

